"""
predict.py — Standalone Heart Disease Prediction Script
========================================================
Loads the pre-trained best model and fitted FeaturePipeline from disk
(generated by main.py) and allows the user to obtain a heart disease
prediction without re-running the full training pipeline.

Usage:
    python predict.py

Prerequisites:
    Run main.py at least once so that:
        outputs/best_model.pkl
        outputs/feature_pipeline.pkl
    exist on disk.
"""

import os
import sys
import joblib
import numpy as np
import pandas as pd

# ---------------------------------------------------------------------------
# Paths — resolve relative to this script regardless of CWD
# ---------------------------------------------------------------------------
_BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH    = os.path.join(_BASE_DIR, 'outputs', 'best_model.pkl')
PIPELINE_PATH = os.path.join(_BASE_DIR, 'outputs', 'feature_pipeline.pkl')

# ---------------------------------------------------------------------------
# The 13 original clinical feature columns (training order must be preserved)
# ---------------------------------------------------------------------------
FEATURE_COLUMNS = [
    'age', 'sex', 'cp', 'trestbps', 'chol',
    'fbs', 'restecg', 'thalach', 'exang',
    'oldpeak', 'slope', 'ca', 'thal'
]

# ---------------------------------------------------------------------------
# Per-feature prompt metadata: (display label, cast type, allowed value set)
# ---------------------------------------------------------------------------
FEATURE_PROMPTS = {
    'age'     : ("Age (years)",                    float, None),
    'sex'     : ("Sex (1 = male, 0 = female)",     int,   {0, 1}),
    'cp'      : ("Chest Pain Type (0-3)",           int,   {0, 1, 2, 3}),
    'trestbps': ("Resting Blood Pressure (mm Hg)", float, None),
    'chol'    : ("Serum Cholesterol (mg/dl)",      float, None),
    'fbs'     : ("Fasting Blood Sugar > 120 mg/dl (1=True, 0=False)", int, {0, 1}),
    'restecg' : ("Resting ECG Results (0-2)",      int,   {0, 1, 2}),
    'thalach' : ("Max Heart Rate Achieved",        float, None),
    'exang'   : ("Exercise Induced Angina (1=Yes, 0=No)", int, {0, 1}),
    'oldpeak' : ("ST Depression (oldpeak)",        float, None),
    'slope'   : ("Slope of Peak Exercise ST (0-2)", int,  {0, 1, 2}),
    'ca'      : ("Number of Major Vessels (0-3)",  int,   {0, 1, 2, 3}),
    'thal'    : ("Thalassemia (0=normal, 1=fixed defect, 2=reversable defect)", int, {0, 1, 2}),
}


# ---------------------------------------------------------------------------
# Load persisted artefacts
# ---------------------------------------------------------------------------
def load_artifacts(model_path: str, pipeline_path: str):
    """
    Load the serialised best model and FeaturePipeline from disk.

    Args:
        model_path   : Absolute path to best_model.pkl.
        pipeline_path: Absolute path to feature_pipeline.pkl.

    Returns:
        tuple: (model, pipeline)

    Raises:
        FileNotFoundError: If either artefact file is missing.
    """
    for path, label in [(model_path, 'Model'), (pipeline_path, 'Pipeline')]:
        if not os.path.exists(path):
            raise FileNotFoundError(
                f"{label} artefact not found at:\n  {path}\n"
                "Please run main.py first to train and save the model."
            )

    model    = joblib.load(model_path)
    pipeline = joblib.load(pipeline_path)
    print(f"  Loaded model    : {model_path}")
    print(f"  Loaded pipeline : {pipeline_path}\n")
    return model, pipeline


# ---------------------------------------------------------------------------
# Collect user input with validation
# ---------------------------------------------------------------------------
def collect_user_input() -> pd.DataFrame:
    """
    Interactively prompt the user to enter all 13 clinical feature values.
    Validates type and allowed-set constraints before accepting each value.

    Returns:
        pd.DataFrame: Single-row DataFrame with correct column names.
    """
    print("\n" + "=" * 60)
    print("          HEART DISEASE PREDICTION — PATIENT INPUT          ")
    print("=" * 60)
    print("Enter the following clinical values for the patient:\n")

    values = {}

    for col in FEATURE_COLUMNS:
        label, dtype, allowed = FEATURE_PROMPTS[col]

        while True:
            try:
                raw = input(f"  {label}: ").strip()

                # Cast to required type
                val = dtype(raw)

                # Validate against allowed discrete set
                if allowed is not None and val not in allowed:
                    print(f"    [!] Invalid value. Allowed: {sorted(allowed)}")
                    continue

                # Basic positivity guard for physiological measurements
                if col in ('age', 'trestbps', 'chol', 'thalach') and val <= 0:
                    print(f"    [!] Value must be positive. Please re-enter.")
                    continue

                values[col] = val
                break

            except ValueError:
                kind = "whole number" if dtype is int else "numeric value"
                print(f"    [!] Invalid input — expected a {kind}. Try again.")

    return pd.DataFrame([values], columns=FEATURE_COLUMNS)


# ---------------------------------------------------------------------------
# Run prediction and display result
# ---------------------------------------------------------------------------
def predict_from_user_input(model, pipeline) -> None:
    """
    Collect patient features, transform them, run the model, and display
    the heart disease prediction with probability.

    Args:
        model   : Loaded sklearn classifier.
        pipeline: Loaded and fitted FeaturePipeline.
    """
    # Step 1: Gather raw inputs
    input_df = collect_user_input()

    # Step 2: Apply saved feature pipeline (no re-fitting)
    try:
        input_transformed = pipeline.transform(input_df)
    except Exception as exc:
        print(f"\n[ERROR] Feature transformation failed: {exc}")
        sys.exit(1)

    # Step 3: Predict label
    try:
        prediction = model.predict(input_transformed)[0]
    except Exception as exc:
        print(f"\n[ERROR] Prediction failed: {exc}")
        sys.exit(1)

    # Step 4: Compute probability
    try:
        if hasattr(model, 'predict_proba'):
            prob = model.predict_proba(input_transformed)[0][1]
        elif hasattr(model, 'decision_function'):
            score = model.decision_function(input_transformed)[0]
            prob  = 1 / (1 + np.exp(-score))   # sigmoid normalisation
        else:
            prob = float(prediction)
    except Exception as exc:
        print(f"\n[WARNING] Could not compute probability: {exc}")
        prob = float(prediction)

    # Step 5: Display result
    print("\n" + "=" * 60)
    print("                     PREDICTION RESULT                     ")
    print("=" * 60)
    print(f"\n  Heart Disease Risk : {prob * 100:.2f}%")

    if prediction == 1:
        verdict = "YES"
        outcome = "YES — Patient is likely to have heart disease."
        color   = "\033[91m"   # Red
    else:
        verdict = "NO"
        outcome = "NO  — Patient is unlikely to have heart disease."
        color   = "\033[92m"   # Green

    reset = "\033[0m"
    print(f"  Prediction        : {color}{verdict}{reset}")
    print(f"\n  Outcome: {outcome}")
    print("=" * 60 + "\n")


# ---------------------------------------------------------------------------
# Optional: Run sample test without user interaction
# ---------------------------------------------------------------------------
def run_sample_prediction(model, pipeline) -> None:
    """
    Run a known reference patient (from the task specification) through
    the pipeline to confirm the saved model is functioning correctly.
    """
    sample = {
        'age'     : 63,
        'sex'     : 1,
        'cp'      : 3,
        'trestbps': 145,
        'chol'    : 233,
        'fbs'     : 1,
        'restecg' : 0,
        'thalach' : 150,
        'exang'   : 0,
        'oldpeak' : 2.3,
        'slope'   : 0,
        'ca'      : 0,
        'thal'    : 1,
    }

    print("\n" + "=" * 60)
    print("           SAMPLE REFERENCE TEST (auto-run)                 ")
    print("=" * 60)
    for k, v in sample.items():
        print(f"  {k:10s}: {v}")

    try:
        df = pd.DataFrame([sample], columns=FEATURE_COLUMNS)
        transformed  = pipeline.transform(df)
        prediction   = model.predict(transformed)[0]

        if hasattr(model, 'predict_proba'):
            prob = model.predict_proba(transformed)[0][1]
        else:
            score = model.decision_function(transformed)[0]
            prob  = 1 / (1 + np.exp(-score))

        print(f"\n  Heart Disease Risk : {prob * 100:.2f}%")
        label = "YES — Patient is likely to have heart disease." \
                if prediction == 1 else "NO  — Patient is unlikely to have heart disease."
        print(f"  Prediction        : {'YES' if prediction == 1 else 'NO'}")
        print(f"  Outcome: {label}")

    except Exception as exc:
        print(f"\n[ERROR] Sample test failed: {exc}")

    print("=" * 60)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
def main():
    print("=" * 60)
    print("         CORDIS — HEART DISEASE PREDICTION TOOL            ")
    print("=" * 60)
    print("\nLoading saved model artefacts...")

    # Load artefacts; exit gracefully if files are missing
    try:
        model, pipeline = load_artifacts(MODEL_PATH, PIPELINE_PATH)
    except FileNotFoundError as exc:
        print(f"\n[ERROR] {exc}")
        sys.exit(1)

    print(f"  Model type: {type(model).__name__}")

    # Run the hardcoded sample test first (sanity check)
    run_sample_prediction(model, pipeline)

    # Interactive patient input loop
    while True:
        predict_from_user_input(model, pipeline)

        again = input("Predict for another patient? (y/n): ").strip().lower()
        if again != 'y':
            print("\nExiting prediction tool. Goodbye!\n")
            break


if __name__ == "__main__":
    main()
